#!/usr/bin/env python

# https://github.com/git/git/blob/master/Documentation/githooks.txt#L63
# This hook is invoked by 'git am'.  It takes no parameter,
# and is invoked after the patch is applied and a commit is made.
# 
# This hook is meant primarily for notification, and cannot affect
# the outcome of 'git am'.
import gitta_hook
import sys
kwargs = {}
gitta_hook.trigger(*sys.argv, **kwargs)

